### ISSUE TITLE
Support for GamezBD

### ISSUE THREAD

**Issue by Bamboozul** [Sehyn/BDO-Toolbox#1]
Add support for **GamezBD client** "Private server".

The location for the folder is"Documents\GamezBD\FaceTexture", or you can simply give us the ability to choose the location manually.

Thank you very much.

**Comment by Sehyn** [comment]
@MrJktra , Update has been pushed (Source code ,Downloads + Credits for contributing updated)

Source files changed: https://github.com/Sehyn/BDO-Toolbox/commit/881669f18342433f25084253c345faab0adc8632
Download: https://github.com/Sehyn/BDO-Toolbox/releases/tag/ENHANCEMENT
Credits added: https://github.com/Sehyn/BDO-Toolbox/commit/ddabc0580f666cc2f737e25ae7ea660237c9e9e8

Thank you for your idea, please try and let me know if it worked properly so I can close the issue else it'll be closed in 48 hours from now.

**Comment by Bamboozul** [comment]
I did test it now and the "FaceTexture" changing works very nicely.
Well done indeed.

**Comment by Sehyn** [comment]
> I did test it now and the "FaceTexture" changing works very nicely.
> 
> Well done indeed.

Thank your for confirming it works properly, let me know if you have any kind of ideas for game modifications or tweaks have fun.
